apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: todo
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
        - name: todo
          image: todo:0.1.0-5c23086-20190109225454
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_COOKIE
              value: "FOOFOOFOO"
            - name: REDIS_SERVER
              value: "some_uri"
