apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: todo
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
        - name: todo
          image: todo:0.1.0-4e6b0a9-20190110192208
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_COOKIE
              value: "FOOFOOFOO"
            - name: REDIS_SERVER
              value: "redis-master"
            - name: REDIS_PASSWORD
              value: "MBHoiesjxM"
            - name: HTTP_PORT
              value: "9090"
